#ifndef __DEFINE_H__
#define __DEFINE_H__



#define SOUND_BOOM		IDR_SOUND1
#define SOUND_GAMEOVER	IDR_SOUND2
#define SOUND_LVUP		IDR_SOUND3
#define SOUND_SEL		IDR_SOUND4
#define SOUND_SELECTED	IDR_SOUND5
#define SOUND_TICK		IDR_SOUND6
#define SOUND_TURN		IDR_SOUND7
#define SOUND_CLRLINE	IDR_SOUND8
#define SOUND_BGM		IDR_SOUND9
#define SOUND_COIN		IDR_SOUND10

#define ARROW_UP 72
#define ARROW_LEFT 75
#define ARROW_RIGHT 77
#define ARROW_DOWN 80
#define ESC_KEY 27
#define ENTER_KEY 13
#define FUNC_KEY 224


#define HCU HKEY_CURRENT_USER
#define HLM HKEY_LOCAL_MACHINE
#define HCR HKEY_CLASSES_ROOT
#define KEY "Software\\YukihoAA\\TETRIS\\"


#define ERROR_MENU_PRINT 0
#define ERROR_MENU_INPUT 1
#define ERROR_BLOCK_PRT 2
#define ERROR_IS_COLLISION 3
#define ERROR_TURN_BLOCK 4
#define ERROR_APPEND_MAP 5
#define ERROR_FMOD_INIT 6
#define ERROR_FMOD_UPDATE 7
#define ERROR_FMOD_LOAD 8
#define ERROR_PLAY_GAME_SOUND 9
#define ERROR_NO_MUSIC_8BIT 10
#define ERROR_NO_MUSIC_ANI 11
#define ERROR_NO_MUSIC_CAT 12
#define ERROR_SETTING_INPUT 13
#define ERROR_MP3_DOWN 14
#define ERROR_RANK_LOAD 15


#define NUM_8BIT 10
#define NUM_ANI 12
#define NUM_CAT 4


#define MAP_X 12
#define MAP_Y 20


#define MAP_MAX_X 11
#define MAP_MAX_Y 19

#define MAP_POS_X 6
#define MAP_POS_Y 4

#define NEW_BLOCK_X 5
#define NEW_BLOCK_Y 0


#define NEXT_BLOCK_POS_X 42
#define NEXT_BLOCK_POS_Y 5

#define NEXT_BLOCK_X 4
#define NEXT_BLOCK_Y 3

#define NNEXT_BLOCK_X 4
#define NNEXT_BLOCK_Y 3

#define NNEXT_BLOCK_POS_X 42
#define NNEXT_BLOCK_POS_Y 12

#define LEVEL_POS_X 44
#define LEVEL_POS_Y 19
#define LINE_POS_X 44
#define LINE_POS_Y 20
#define SCORE_POS_X 44
#define SCORE_POS_Y 22
#define BEST_POS_X 49
#define BEST_POS_Y 23




#endif